In [2]:
from pathlib import Path
import pandas as pd

In [3]:
PROJECT_ROOT = Path.cwd().parent

RAW_DATA= PROJECT_ROOT / "data" / "raw"

In [4]:
for folder in RAW_DATA.iterdir():
    print("\n" + "=" * 60)
    print(folder.name)

    for file in folder.iterdir():
        print("  ", file.name)

============================================================
anime_dataset
   anime-dataset-2023.csv
   anime-filtered.csv
   final_animedataset.csv
   user-filtered.csv
   users-details-2023.csv
   users-score-2023.csv

============================================================
ml-1m
   movies.dat
   ratings.dat
   README
   users.dat

============================================================
movies_csv
   credits_clean.csv
   dim_items.parquet
   fact_interactions.csv
   item_cast.csv
   item_directors.csv
   item_genres.csv
   item_keywords.csv
   keywords_clean.csv
   links_clean.csv
   movies_metadata_clean.csv

============================================================
movies_dataset
   credits.csv
   keywords.csv
   links.csv
   links_small.csv
   movies_metadata.csv
   ratings.csv
   ratings_small.csv

============================================================
tvshows_dataset
   TMDB_tv_dataset_v3.csv

In [5]:
movies_metadata = pd.read_csv(
    RAW_DATA / "movies_dataset" / "movies_metadata.csv",
    low_memory=False
)

credits = pd.read_csv(
    RAW_DATA / "movies_dataset" / "credits.csv"
)

keywords = pd.read_csv(
    RAW_DATA / "movies_dataset" / "keywords.csv"
)

links = pd.read_csv(
    RAW_DATA / "movies_dataset" / "links.csv"
)

ratings = pd.read_csv(
    RAW_DATA / "movies_dataset" / "ratings.csv"
)

anime = pd.read_csv(
    RAW_DATA / "anime_dataset" / "anime-dataset-2023.csv"
)

anime_scores = pd.read_csv(
    RAW_DATA / "anime_dataset" / "users-score-2023.csv"
)

anime_users = pd.read_csv(
    RAW_DATA / "anime_dataset" / "users-details-2023.csv"
)

tvshows = pd.read_csv(
    RAW_DATA / "tvshows_dataset" / "TMDB_tv_dataset_v3.csv"
)

In [6]:
for name, df in {
    "movies_metadata": movies_metadata,
    "credits": credits,
    "keywords": keywords,
    "links": links,
    "ratings": ratings,
    "anime": anime,
    "anime_scores": anime_scores,
    "anime_users": anime_users,
    "tvshows": tvshows
}.items():

    print(f"\n{name}")
    print("-" * 50)

    print("Shape:", df.shape)

movies_metadata
--------------------------------------------------
Shape: (45466, 24)

credits
--------------------------------------------------
Shape: (45476, 3)

keywords
--------------------------------------------------
Shape: (46419, 2)

links
--------------------------------------------------
Shape: (45843, 3)

ratings
--------------------------------------------------
Shape: (26024289, 4)

anime
--------------------------------------------------
Shape: (24905, 24)

anime_scores
--------------------------------------------------
Shape: (24325191, 5)

anime_users
--------------------------------------------------
Shape: (731290, 16)

tvshows
--------------------------------------------------
Shape: (168639, 29)

In [7]:
import fastparquet

In [8]:
dim_items = pd.read_parquet(f"{PROJECT_ROOT}/data/processed/movies/dim_items.parquet")

In [9]:
item_genres = pd.read_parquet(f"{PROJECT_ROOT}/data/processed/movies/item_genres.parquet")

In [10]:
content_features = pd.read_parquet(f"{PROJECT_ROOT}/data/processed/movies/content_features.parquet")

In [11]:
dim_items.head()

,item_id,source_item_id,title,description,release_date,runtime,language,popularity,vote_average,vote_count,collection_name,company_names,country_names,budget,revenue,poster_path,domain
0,1,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",1995-10-30,81.0,en,21.946943,7.7,5415.0,Toy Story Collection,Pixar Animation Studios,United States of America,30000000,373554033.0,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,movie
1,2,8844,Jumanji,When siblings Judy and Peter discover an encha...,1995-12-15,104.0,en,17.015539,6.9,2413.0,,TriStar Pictures Teitler Film Interscope Commu...,United States of America,65000000,262797249.0,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,movie
2,3,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,1995-12-22,101.0,en,11.712900,6.5,92.0,Grumpy Old Men Collection,Warner Bros. Lancaster Gate,United States of America,0,0.0,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,movie
3,4,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",1995-12-22,127.0,en,3.859495,6.1,34.0,,Twentieth Century Fox Film Corporation,United States of America,16000000,81452156.0,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,movie
4,5,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,1995-02-10,106.0,en,8.387519,5.7,173.0,Father of the Bride Collection,Sandollar Productions Touchstone Pictures,United States of America,0,76578911.0,/e64sOI48hQXyru7naBFyssKFxVd.jpg,movie

In [12]:
item_genres.head()

   item_id      genre
0        1  Animation
1        1     Comedy
2        1     Family
3        2  Adventure
4        2    Fantasy

In [13]:
content_features.head()

,item_id,source_item_id,title,description,collection_name,company_names,country_names,domain,genres,keywords,directors,actors,content_text
0,1,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Toy Story Collection,Pixar Animation Studios,United States of America,movie,Animation Comedy Family,boy boy next door friends friendship jealousy ...,John Lasseter,Don Rickles Jim Varney Tim Allen Tom Hanks Wal...,"Led by Woody, Andy's toys live happily in his ..."
1,2,8844,Jumanji,When siblings Judy and Peter discover an encha...,,TriStar Pictures Teitler Film Interscope Commu...,United States of America,movie,Adventure Family Fantasy,based on children's book board game disappeara...,Joe Johnston,Bonnie Hunt Bradley Pierce Jonathan Hyde Kirst...,When siblings Judy and Peter discover an encha...
2,3,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,Grumpy Old Men Collection,Warner Bros. Lancaster Gate,United States of America,movie,Comedy Romance,best friend duringcreditsstinger fishing old men,Howard Deutch,Ann-Margret Daryl Hannah Jack Lemmon Sophia Lo...,A family wedding reignites the ancient feud be...
3,4,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",,Twentieth Century Fox Film Corporation,United States of America,movie,Comedy Drama Romance,based on novel chick flick divorce interracial...,Forest Whitaker,Angela Bassett Gregory Hines Lela Rochon Loret...,"Cheated on, mistreated and stepped on, the wom..."
4,5,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,Father of the Bride Collection,Sandollar Productions Touchstone Pictures,United States of America,movie,Comedy,aging baby confidence contraception daughter g...,Charles Shyer,Diane Keaton George Newbern Kimberly Williams-...,Just when George Banks has recovered from his ...

In [14]:
dim_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 45430 entries, 0 to 45429
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   item_id          45430 non-null  int64
 1   source_item_id   45430 non-null  int64
 2   title            45430 non-null  str
 3   description      44476 non-null  str
 4   release_date     45346 non-null  str
 5   runtime          45173 non-null  float64
 6   language         45430 non-null  str
 7   popularity       45430 non-null  float64
 8   vote_average     45430 non-null  float64
 9   vote_count       45430 non-null  float64
 10  collection_name  45430 non-null  str
 11  company_names    45430 non-null  str
 12  country_names    45430 non-null  str
 13  budget           45430 non-null  int64
 14  revenue          45430 non-null  float64
 15  poster_path      45047 non-null  str
 16  domain           45430 non-null  str
dtypes: float64(5), int64(3), str(9)
memory usage: 24.6 MB

In [15]:
content_features.info()

<class 'pandas.DataFrame'>
RangeIndex: 45430 entries, 0 to 45429
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   item_id          45430 non-null  int64
 1   source_item_id   45430 non-null  int64
 2   title            45430 non-null  str
 3   description      45430 non-null  str
 4   collection_name  45430 non-null  str
 5   company_names    45430 non-null  str
 6   country_names    45430 non-null  str
 7   domain           45430 non-null  str
 8   genres           45430 non-null  str
 9   keywords         45430 non-null  str
 10  directors        45430 non-null  str
 11  actors           45430 non-null  str
 12  content_text     45430 non-null  str
dtypes: int64(2), str(11)
memory usage: 48.6 MB

In [17]:
movie_features = content_features.merge(
    dim_items[["item_id", "release_date", "runtime", "language", "popularity", "vote_average", "vote_count", "budget", "revenue", "poster_path"]],
    on = "item_id",
    how = "inner"
)

In [18]:
movie_features.info()

<class 'pandas.DataFrame'>
RangeIndex: 45430 entries, 0 to 45429
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   item_id          45430 non-null  int64
 1   source_item_id   45430 non-null  int64
 2   title            45430 non-null  str
 3   description      45430 non-null  str
 4   collection_name  45430 non-null  str
 5   company_names    45430 non-null  str
 6   country_names    45430 non-null  str
 7   domain           45430 non-null  str
 8   genres           45430 non-null  str
 9   keywords         45430 non-null  str
 10  directors        45430 non-null  str
 11  actors           45430 non-null  str
 12  content_text     45430 non-null  str
 13  release_date     45346 non-null  str
 14  runtime          45173 non-null  float64
 15  language         45430 non-null  str
 16  popularity       45430 non-null  float64
 17  vote_average     45430 non-null  float64
 18  vote_count       45430 non-null  float64
 19  budget           45430 non-null  int64
 20  revenue          45430 non-null  float64
 21  poster_path      45047 non-null  str
dtypes: float64(5), int64(3), str(14)
memory usage: 53.6 MB

In [19]:
movie_features.head()

,item_id,source_item_id,title,description,collection_name,company_names,country_names,domain,genres,keywords,directors,actors,content_text,release_date,runtime,language,popularity,vote_average,vote_count,budget,revenue,poster_path
0,1,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Toy Story Collection,Pixar Animation Studios,United States of America,movie,Animation Comedy Family,boy boy next door friends friendship jealousy ...,John Lasseter,Don Rickles Jim Varney Tim Allen Tom Hanks Wal...,"Led by Woody, Andy's toys live happily in his ...",1995-10-30,81.0,en,21.946943,7.7,5415.0,30000000,373554033.0,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg
1,2,8844,Jumanji,When siblings Judy and Peter discover an encha...,,TriStar Pictures Teitler Film Interscope Commu...,United States of America,movie,Adventure Family Fantasy,based on children's book board game disappeara...,Joe Johnston,Bonnie Hunt Bradley Pierce Jonathan Hyde Kirst...,When siblings Judy and Peter discover an encha...,1995-12-15,104.0,en,17.015539,6.9,2413.0,65000000,262797249.0,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg
2,3,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,Grumpy Old Men Collection,Warner Bros. Lancaster Gate,United States of America,movie,Comedy Romance,best friend duringcreditsstinger fishing old men,Howard Deutch,Ann-Margret Daryl Hannah Jack Lemmon Sophia Lo...,A family wedding reignites the ancient feud be...,1995-12-22,101.0,en,11.712900,6.5,92.0,0,0.0,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg
3,4,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",,Twentieth Century Fox Film Corporation,United States of America,movie,Comedy Drama Romance,based on novel chick flick divorce interracial...,Forest Whitaker,Angela Bassett Gregory Hines Lela Rochon Loret...,"Cheated on, mistreated and stepped on, the wom...",1995-12-22,127.0,en,3.859495,6.1,34.0,16000000,81452156.0,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg
4,5,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,Father of the Bride Collection,Sandollar Productions Touchstone Pictures,United States of America,movie,Comedy,aging baby confidence contraception daughter g...,Charles Shyer,Diane Keaton George Newbern Kimberly Williams-...,Just when George Banks has recovered from his ...,1995-02-10,106.0,en,8.387519,5.7,173.0,0,76578911.0,/e64sOI48hQXyru7naBFyssKFxVd.jpg

In [20]:
movie_features.to_parquet(
    f"{PROJECT_ROOT}/data/processed/movies/movie_features.parquet"
)

In [21]:
movie_features["release_year"] = pd.to_datetime(movie_features["release_date"]).dt.year

In [25]:
movie_features["release_year"] = movie_features["release_year"].astype("Int64")

In [26]:
movie_features.info()

<class 'pandas.DataFrame'>
RangeIndex: 45430 entries, 0 to 45429
Data columns (total 23 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   item_id          45430 non-null  int64
 1   source_item_id   45430 non-null  int64
 2   title            45430 non-null  str
 3   description      45430 non-null  str
 4   collection_name  45430 non-null  str
 5   company_names    45430 non-null  str
 6   country_names    45430 non-null  str
 7   domain           45430 non-null  str
 8   genres           45430 non-null  str
 9   keywords         45430 non-null  str
 10  directors        45430 non-null  str
 11  actors           45430 non-null  str
 12  content_text     45430 non-null  str
 13  release_date     45346 non-null  str
 14  runtime          45173 non-null  float64
 15  language         45430 non-null  str
 16  popularity       45430 non-null  float64
 17  vote_average     45430 non-null  float64
 18  vote_count       45430 non-null  float64
 19  budget           45430 non-null  int64
 20  revenue          45430 non-null  float64
 21  poster_path      45047 non-null  str
 22  release_year     45346 non-null  Int64
dtypes: Int64(1), float64(5), int64(3), str(14)
memory usage: 54.0 MB

In [27]:
movie_features.head()

,item_id,source_item_id,title,description,collection_name,company_names,country_names,domain,genres,keywords,directors,actors,content_text,release_date,runtime,language,popularity,vote_average,vote_count,budget,revenue,poster_path,release_year
0,1,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Toy Story Collection,Pixar Animation Studios,United States of America,movie,Animation Comedy Family,boy boy next door friends friendship jealousy ...,John Lasseter,Don Rickles Jim Varney Tim Allen Tom Hanks Wal...,"Led by Woody, Andy's toys live happily in his ...",1995-10-30,81.0,en,21.946943,7.7,5415.0,30000000,373554033.0,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,1995
1,2,8844,Jumanji,When siblings Judy and Peter discover an encha...,,TriStar Pictures Teitler Film Interscope Commu...,United States of America,movie,Adventure Family Fantasy,based on children's book board game disappeara...,Joe Johnston,Bonnie Hunt Bradley Pierce Jonathan Hyde Kirst...,When siblings Judy and Peter discover an encha...,1995-12-15,104.0,en,17.015539,6.9,2413.0,65000000,262797249.0,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,1995
2,3,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,Grumpy Old Men Collection,Warner Bros. Lancaster Gate,United States of America,movie,Comedy Romance,best friend duringcreditsstinger fishing old men,Howard Deutch,Ann-Margret Daryl Hannah Jack Lemmon Sophia Lo...,A family wedding reignites the ancient feud be...,1995-12-22,101.0,en,11.712900,6.5,92.0,0,0.0,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,1995
3,4,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",,Twentieth Century Fox Film Corporation,United States of America,movie,Comedy Drama Romance,based on novel chick flick divorce interracial...,Forest Whitaker,Angela Bassett Gregory Hines Lela Rochon Loret...,"Cheated on, mistreated and stepped on, the wom...",1995-12-22,127.0,en,3.859495,6.1,34.0,16000000,81452156.0,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,1995
4,5,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,Father of the Bride Collection,Sandollar Productions Touchstone Pictures,United States of America,movie,Comedy,aging baby confidence contraception daughter g...,Charles Shyer,Diane Keaton George Newbern Kimberly Williams-...,Just when George Banks has recovered from his ...,1995-02-10,106.0,en,8.387519,5.7,173.0,0,76578911.0,/e64sOI48hQXyru7naBFyssKFxVd.jpg,1995

In [36]:
movie_features.to_parquet(
    f"{PROJECT_ROOT}/data/processed/movies/movie_master.parquet"
)

In [30]:
movie_features["genres"].head()

0     Animation Comedy Family
1    Adventure Family Fantasy
2              Comedy Romance
3        Comedy Drama Romance
4                      Comedy
Name: genres, dtype: str

In [31]:
movie_features["display_title"] = (
    movie_features["title"].fillna("")
    + " ("
    + movie_features["release_year"]
        .fillna(0)
        .astype(int)
        .astype(str)
    + ")"
)

In [35]:
movie_features["search_text"]

0                          toy story
1                            jumanji
2                   grumpier old men
3                  waiting to exhale
4        father of the bride part ii
                    ...
45425                         subdue
45426            century of birthing
45427                       betrayal
45428               satan triumphant
45429                       queerama
Name: search_text, Length: 45430, dtype: str

In [34]:
movie_features["search_text"] = (
    movie_features["title"]
    .fillna("")
    .str.lower()
)