In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import ast

In [2]:
PROJECT_ROOT = Path.cwd().parent

RAW_DATA= PROJECT_ROOT / "data" / "raw"

In [3]:
movies_metadata = pd.read_csv(
    RAW_DATA / "movies_dataset" / "movies_metadata.csv",
    low_memory=False
)

credits = pd.read_csv(
    RAW_DATA / "movies_dataset" / "credits.csv"
)

keywords = pd.read_csv(
    RAW_DATA / "movies_dataset" / "keywords.csv"
)

links = pd.read_csv(
    RAW_DATA / "movies_dataset" / "links.csv"
)

ratings = pd.read_csv(
    RAW_DATA / "movies_dataset" / "ratings.csv"
)

In [4]:
ratings.info()

<class 'pandas.DataFrame'>
RangeIndex: 26024289 entries, 0 to 26024288
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  int64
dtypes: float64(1), int64(3)
memory usage: 794.2 MB

In [5]:
movies_metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  str
 1   belongs_to_collection  4494 non-null   str
 2   budget                 45466 non-null  str
 3   genres                 45466 non-null  str
 4   homepage               7782 non-null   str
 5   id                     45466 non-null  str
 6   imdb_id                45449 non-null  str
 7   original_language      45455 non-null  str
 8   original_title         45466 non-null  str
 9   overview               44512 non-null  str
 10  popularity             45461 non-null  str
 11  poster_path            45080 non-null  str
 12  production_companies   45463 non-null  str
 13  production_countries   45463 non-null  str
 14  release_date           45379 non-null  str
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  str
 18  status                 45379 non-null  str
 19  tagline                20412 non-null  str
 20  title                  45460 non-null  str
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(1), str(19)
memory usage: 8.3+ MB

In [6]:
keywords.info()

<class 'pandas.DataFrame'>
RangeIndex: 46419 entries, 0 to 46418
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        46419 non-null  int64
 1   keywords  46419 non-null  str
dtypes: int64(1), str(1)
memory usage: 725.4 KB

In [7]:
credits.info()

<class 'pandas.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45476 non-null  str
 1   crew    45476 non-null  str
 2   id      45476 non-null  int64
dtypes: int64(1), str(2)
memory usage: 1.0 MB

## Links

In [44]:
links.info()

<class 'pandas.DataFrame'>
RangeIndex: 45843 entries, 0 to 45842
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  45843 non-null  int64
 1   imdbId   45843 non-null  int64
 2   tmdbId   45624 non-null  float64
dtypes: float64(1), int64(2)
memory usage: 1.0 MB

In [45]:
links['tmdbId'].isnull().sum()

np.int64(219)

In [46]:
links_clean = links.dropna(subset=["tmdbId"]).copy()

In [56]:
links_clean.info()

<class 'pandas.DataFrame'>
Index: 45624 entries, 0 to 45842
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  45624 non-null  int64
 1   tmdbId   45624 non-null  int64
dtypes: int64(2)
memory usage: 1.0 MB

In [48]:
links_clean['tmdbId'].duplicated().sum()

np.int64(30)

In [50]:
links_clean['tmdbId'].nunique()

45594

In [51]:
links_clean['movieId'].duplicated().sum()

np.int64(0)

In [52]:
links_clean['movieId'].nunique()

45624

In [53]:
links_clean["tmdbId"] = links_clean["tmdbId"].astype(int)

In [55]:
links_clean = links_clean[
    ["movieId", "tmdbId"]
]

In [57]:
links_clean = links_clean.rename(
    columns={
        "movieId": "movie_id",
        "tmdbId": "source_item_id",
    }
)

In [58]:
links_clean.info()

<class 'pandas.DataFrame'>
Index: 45624 entries, 0 to 45842
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   movie_id        45624 non-null  int64
 1   source_item_id  45624 non-null  int64
dtypes: int64(2)
memory usage: 1.0 MB

In [64]:
links_clean.head()

   movie_id  source_item_id
0         1             862
1         2            8844
2         3           15602
3         4           31357
4         5           11862

In [66]:
dup_tmdb = (
    links_clean[
        links_clean["source_item_id"].duplicated(keep=False)
    ]
    .sort_values("source_item_id")
)

dup_tmdb.head(10)

       movie_id  source_item_id
5905       6003            4912
34144    144606            4912
9215      27136            5511
7388       7587            5511
45197    174533           10991
4148       4241           10991
14089     70545           11115
25138    116752           11115
45202    174543           12600
5574       5672           12600

In [75]:
links_clean.to_csv(
    "links_clean.csv",
    index=False
)

In [12]:
links_clean = pd.read_csv("links_clean.csv")

## ratings

In [7]:
ratings.info(show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 26024289 entries, 0 to 26024288
Data columns (total 4 columns):
 #   Column     Non-Null Count     Dtype
---  ------     --------------     -----
 0   userId     26024289 non-null  int64
 1   movieId    26024289 non-null  int64
 2   rating     26024289 non-null  float64
 3   timestamp  26024289 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 794.2 MB

In [20]:
ratings.head()

   userId  movie_id  rating   timestamp
0       1       110     1.0  1425941529
1       1       147     4.5  1425942435
2       1       858     5.0  1425941523
3       1      1221     5.0  1425941546
4       1      1246     5.0  1425941556

In [8]:
ratings["userId"].nunique()

270896

In [9]:
ratings["movieId"].nunique()

45115

In [10]:
ratings["rating"].describe()

count    2.602429e+07
mean     3.528090e+00
std      1.065443e+00
min      5.000000e-01
25%      3.000000e+00
50%      3.500000e+00
75%      4.000000e+00
max      5.000000e+00
Name: rating, dtype: float64

In [14]:
ratings["movieId"].isin(
    links_clean["movie_id"]
).mean()

np.float64(0.9994811385625175)

In [16]:
links_clean.head()

   movie_id  source_item_id
0         1             862
1         2            8844
2         3           15602
3         4           31357
4         5           11862

In [19]:
ratings = ratings.rename(
    columns={"movieId": "movie_id"}
)

In [21]:
fact_interactions = ratings.merge(
    links_clean,
    on ="movie_id",
    how="inner"
)

In [22]:
fact_interactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 26010786 entries, 0 to 26010785
Data columns (total 5 columns):
 #   Column          Dtype
---  ------          -----
 0   userId          int64
 1   movie_id        int64
 2   rating          float64
 3   timestamp       int64
 4   source_item_id  int64
dtypes: float64(1), int64(4)
memory usage: 992.2 MB

In [23]:
fact_interactions = fact_interactions[
    [
        "userId",
        "source_item_id",
        "rating",
        "timestamp"
    ]
]

In [24]:
fact_interactions = fact_interactions.rename(
    columns={
        "userId": "user_id"
    }
)

In [25]:
fact_interactions.info(show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 26010786 entries, 0 to 26010785
Data columns (total 4 columns):
 #   Column          Non-Null Count     Dtype
---  ------          --------------     -----
 0   user_id         26010786 non-null  int64
 1   source_item_id  26010786 non-null  int64
 2   rating          26010786 non-null  float64
 3   timestamp       26010786 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 793.8 MB

In [26]:
fact_interactions.head()

   user_id  source_item_id  rating   timestamp
0        1             197     1.0  1425941529
1        1           10474     4.5  1425942435
2        1             238     5.0  1425941523
3        1             240     5.0  1425941546
4        1             207     5.0  1425941556

In [27]:
movies_metadata_clean = pd.read_csv("movies_metadata_clean.csv")

In [28]:
missing_movies = (
    ~fact_interactions["source_item_id"]
      .isin(movies_metadata_clean["source_item_id"])
).sum()

print(missing_movies)

29219

In [29]:
fact_interactions["user_id"] = fact_interactions["user_id"].astype("int32")
fact_interactions["source_item_id"] = fact_interactions["source_item_id"].astype("int32")
fact_interactions["rating"] = fact_interactions["rating"].astype("float32")
fact_interactions["timestamp"] = fact_interactions["timestamp"].astype("int64")

In [31]:
fact_interactions.info(show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 26010786 entries, 0 to 26010785
Data columns (total 4 columns):
 #   Column          Non-Null Count     Dtype
---  ------          --------------     -----
 0   user_id         26010786 non-null  int32
 1   source_item_id  26010786 non-null  int32
 2   rating          26010786 non-null  float32
 3   timestamp       26010786 non-null  int64
dtypes: float32(1), int32(2), int64(1)
memory usage: 496.1 MB

In [ ]:
fact_interactions.to_csv(
    "fact_interactions.csv",
    index=False
)

## movies_metadata

In [78]:
movies_metadata_clean = movies_metadata.copy()

In [79]:
movies_metadata_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  str
 1   belongs_to_collection  4494 non-null   str
 2   budget                 45466 non-null  str
 3   genres                 45466 non-null  str
 4   homepage               7782 non-null   str
 5   id                     45466 non-null  str
 6   imdb_id                45449 non-null  str
 7   original_language      45455 non-null  str
 8   original_title         45466 non-null  str
 9   overview               44512 non-null  str
 10  popularity             45461 non-null  str
 11  poster_path            45080 non-null  str
 12  production_companies   45463 non-null  str
 13  production_countries   45463 non-null  str
 14  release_date           45379 non-null  str
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  str
 18  status                 45379 non-null  str
 19  tagline                20412 non-null  str
 20  title                  45460 non-null  str
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(1), str(19)
memory usage: 8.3+ MB

In [86]:
keep_cols = [
    "id",
    "title",
    "overview",
    "genres",
    "release_date",
    "runtime",
    "original_language",
    "popularity",
    "vote_average",
    "vote_count",
    "belongs_to_collection",
    "production_companies",
    "production_countries",
    "budget",
    "revenue",
    "poster_path"
]

movies_metadata_clean = movies_metadata_clean[keep_cols].copy()

In [87]:
movies_metadata_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     45466 non-null  str
 1   title                  45460 non-null  str
 2   overview               44512 non-null  str
 3   genres                 45466 non-null  str
 4   release_date           45379 non-null  str
 5   runtime                45203 non-null  float64
 6   original_language      45455 non-null  str
 7   popularity             45461 non-null  str
 8   vote_average           45460 non-null  float64
 9   vote_count             45460 non-null  float64
 10  belongs_to_collection  4494 non-null   str
 11  production_companies   45463 non-null  str
 12  production_countries   45463 non-null  str
 13  budget                 45466 non-null  str
 14  revenue                45460 non-null  float64
 15  poster_path            45080 non-null  str
dtypes: float64(4), str(12)
memory usage: 5.6 MB

In [88]:
movies_metadata_clean.isnull().sum().sort_values(ascending=False)

belongs_to_collection    40972
overview                   954
poster_path                386
runtime                    263
release_date                87
original_language           11
title                        6
vote_count                   6
revenue                      6
vote_average                 6
popularity                   5
production_companies         3
production_countries         3
genres                       0
id                           0
budget                       0
dtype: int64

In [89]:
invalid_ids = movies_metadata_clean[
    ~movies_metadata_clean["id"].astype(str).str.match(r"^\d+$")
]

print("Invalid IDs:", len(invalid_ids))

invalid_ids[["id", "title"]]

Invalid IDs: 3

               id title
19730  1997-08-20   NaN
29503  2012-09-29   NaN
35587  2014-01-01   NaN

In [90]:
movies_metadata_clean["id"].duplicated().sum()

np.int64(30)

In [ ]:
movies_metadata_clean[
    movies_metadata_clean["id"].duplicated(keep=False)
].sort_values("id").head(2)

In [93]:
movies_metadata_clean = movies_metadata_clean[
    movies_metadata_clean["id"].astype(str).str.match(r"^\d+$")
].copy()

In [105]:
movies_metadata_clean.info()

<class 'pandas.DataFrame'>
Index: 45433 entries, 0 to 45465
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     45433 non-null  int64
 1   title                  45430 non-null  str
 2   overview               45433 non-null  str
 3   genres                 45433 non-null  str
 4   release_date           45346 non-null  str
 5   runtime                45173 non-null  float64
 6   original_language      45422 non-null  str
 7   popularity             45430 non-null  float64
 8   vote_average           45430 non-null  float64
 9   vote_count             45430 non-null  float64
 10  belongs_to_collection  45433 non-null  str
 11  production_companies   45430 non-null  str
 12  production_countries   45430 non-null  str
 13  budget                 45433 non-null  str
 14  revenue                45430 non-null  float64
 15  poster_path            45047 non-null  str
dtypes: float64(5), int64(1), str(10)
memory usage: 5.9 MB

In [96]:
movies_metadata_clean["id"] = (
    movies_metadata_clean["id"]
    .astype(int)
)

In [98]:
movies_metadata_clean = (
    movies_metadata_clean
    .drop_duplicates(subset=["id"])
)

In [100]:
movies_metadata_clean["overview"] = (
    movies_metadata_clean["overview"]
    .fillna("")
)

In [102]:
movies_metadata_clean["belongs_to_collection"] = (
    movies_metadata_clean["belongs_to_collection"]
    .fillna("")
)

In [104]:
movies_metadata_clean["popularity"] = pd.to_numeric(
    movies_metadata_clean["popularity"],
    errors="coerce"
)

In [107]:
movies_metadata_clean["budget"] = pd.to_numeric(
    movies_metadata_clean["budget"],
    errors="coerce"
)

In [109]:
movies_metadata_clean["release_date"] = pd.to_datetime(
    movies_metadata_clean["release_date"],
    errors="coerce"
)

In [110]:
movies_metadata_clean.isnull().sum().sort_values(ascending=False)

poster_path              386
runtime                  260
release_date              87
original_language         11
popularity                 3
production_companies       3
vote_average               3
title                      3
revenue                    3
production_countries       3
vote_count                 3
genres                     0
overview                   0
id                         0
belongs_to_collection      0
budget                     0
dtype: int64

In [111]:
movies_metadata_clean = movies_metadata_clean.dropna(
    subset=["title"]
)

In [112]:
# Fill small missing values
movies_metadata_clean["original_language"] = (
    movies_metadata_clean["original_language"]
    .fillna("unknown")
)

movies_metadata_clean["popularity"] = (
    movies_metadata_clean["popularity"]
    .fillna(0)
)

movies_metadata_clean["vote_average"] = (
    movies_metadata_clean["vote_average"]
    .fillna(0)
)

movies_metadata_clean["vote_count"] = (
    movies_metadata_clean["vote_count"]
    .fillna(0)
)

movies_metadata_clean["revenue"] = (
    movies_metadata_clean["revenue"]
    .fillna(0)
)

movies_metadata_clean["production_companies"] = (
    movies_metadata_clean["production_companies"]
    .fillna("")
)

movies_metadata_clean["production_countries"] = (
    movies_metadata_clean["production_countries"]
    .fillna("")
)

In [113]:
movies_metadata_clean = movies_metadata_clean.rename(
    columns={
        "id": "source_item_id",
        "overview": "description",
        "original_language": "language"
    }
)

movies_metadata_clean["domain"] = "movie"

In [114]:
movies_metadata_clean.info()

<class 'pandas.DataFrame'>
Index: 45430 entries, 0 to 45465
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   source_item_id         45430 non-null  int64
 1   title                  45430 non-null  str
 2   description            45430 non-null  str
 3   genres                 45430 non-null  str
 4   release_date           45346 non-null  datetime64[us]
 5   runtime                45173 non-null  float64
 6   language               45430 non-null  str
 7   popularity             45430 non-null  float64
 8   vote_average           45430 non-null  float64
 9   vote_count             45430 non-null  float64
 10  belongs_to_collection  45430 non-null  str
 11  production_companies   45430 non-null  str
 12  production_countries   45430 non-null  str
 13  budget                 45430 non-null  int64
 14  revenue                45430 non-null  float64
 15  poster_path            45047 non-null  str
 16  domain                 45430 non-null  str
dtypes: datetime64[us](1), float64(5), int64(2), str(9)
memory usage: 6.2 MB

In [116]:
movies_metadata_clean.head()

,source_item_id,title,description,genres,release_date,runtime,language,popularity,vote_average,vote_count,belongs_to_collection,production_companies,production_countries,budget,revenue,poster_path,domain
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",1995-10-30,81.0,en,21.946943,7.7,5415.0,"{'id': 10194, 'name': 'Toy Story Collection', ...","[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",30000000,373554033.0,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,movie
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",1995-12-15,104.0,en,17.015539,6.9,2413.0,,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",65000000,262797249.0,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,movie
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",1995-12-22,101.0,en,11.712900,6.5,92.0,"{'id': 119050, 'name': 'Grumpy Old Men Collect...","[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",0,0.0,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,movie
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",1995-12-22,127.0,en,3.859495,6.1,34.0,,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",16000000,81452156.0,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,movie
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",1995-02-10,106.0,en,8.387519,5.7,173.0,"{'id': 96871, 'name': 'Father of the Bride Col...","[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",0,76578911.0,/e64sOI48hQXyru7naBFyssKFxVd.jpg,movie

In [118]:
movies_metadata_clean.to_csv(
    "movies_metadata_clean.csv",
    index=False
)

In [189]:
import ast

def extract_genres(genre_str):
    try:
        genres = ast.literal_eval(genre_str)
        return [g["name"] for g in genres]
    except:
        return []

In [190]:
movies_metadata_clean["genre_list"] = (
    movies_metadata_clean["genres"]
    .apply(extract_genres)
)

In [191]:
item_genres = (
    movies_metadata_clean[
        ["source_item_id", "genre_list"]
    ]
    .explode("genre_list")
    .rename(
        columns={
            "genre_list": "genre"
        }
    )
)

In [193]:
item_genres = item_genres[
    item_genres["genre"].notna()
]

In [194]:
item_genres.info()

<class 'pandas.DataFrame'>
Index: 91006 entries, 0 to 45463
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   source_item_id  91006 non-null  int64
 1   genre           91006 non-null  str
dtypes: int64(1), str(1)
memory usage: 2.1 MB

In [195]:
item_genres["source_item_id"].nunique()

42988

In [196]:
item_genres.head()

   source_item_id      genre
0             862  Animation
0             862     Comedy
0             862     Family
1            8844  Adventure
1            8844    Fantasy

In [197]:
item_genres.to_csv(
    "item_genres.csv",
    index=False
)

In [33]:
movies_metadata_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 45430 entries, 0 to 45429
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   source_item_id         45430 non-null  int64
 1   title                  45430 non-null  str
 2   description            44476 non-null  str
 3   genres                 45430 non-null  str
 4   release_date           45346 non-null  str
 5   runtime                45173 non-null  float64
 6   language               45430 non-null  str
 7   popularity             45430 non-null  float64
 8   vote_average           45430 non-null  float64
 9   vote_count             45430 non-null  float64
 10  belongs_to_collection  4487 non-null   str
 11  production_companies   45430 non-null  str
 12  production_countries   45430 non-null  str
 13  budget                 45430 non-null  int64
 14  revenue                45430 non-null  float64
 15  poster_path            45047 non-null  str
 16  domain                 45430 non-null  str
dtypes: float64(5), int64(2), str(10)
memory usage: 5.9 MB

In [35]:
movies_metadata_clean.head()

,source_item_id,title,description,genres,release_date,runtime,language,popularity,vote_average,vote_count,belongs_to_collection,production_companies,production_countries,budget,revenue,poster_path,domain
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",1995-10-30,81.0,en,21.946943,7.7,5415.0,"{'id': 10194, 'name': 'Toy Story Collection', ...","[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",30000000,373554033.0,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,movie
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",1995-12-15,104.0,en,17.015539,6.9,2413.0,NaN,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",65000000,262797249.0,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,movie
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",1995-12-22,101.0,en,11.712900,6.5,92.0,"{'id': 119050, 'name': 'Grumpy Old Men Collect...","[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",0,0.0,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,movie
3,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",1995-12-22,127.0,en,3.859495,6.1,34.0,NaN,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",16000000,81452156.0,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,movie
4,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",1995-02-10,106.0,en,8.387519,5.7,173.0,"{'id': 96871, 'name': 'Father of the Bride Col...","[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",0,76578911.0,/e64sOI48hQXyru7naBFyssKFxVd.jpg,movie

In [36]:
dim_items = movies_metadata_clean.copy()

In [37]:
dim_items.insert(
    0,
    "item_id",
    range(1, len(dim_items) + 1)
)

In [39]:
dim_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 45430 entries, 0 to 45429
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   item_id                45430 non-null  int64
 1   source_item_id         45430 non-null  int64
 2   title                  45430 non-null  str
 3   description            44476 non-null  str
 4   genres                 45430 non-null  str
 5   release_date           45346 non-null  str
 6   runtime                45173 non-null  float64
 7   language               45430 non-null  str
 8   popularity             45430 non-null  float64
 9   vote_average           45430 non-null  float64
 10  vote_count             45430 non-null  float64
 11  belongs_to_collection  4487 non-null   str
 12  production_companies   45430 non-null  str
 13  production_countries   45430 non-null  str
 14  budget                 45430 non-null  int64
 15  revenue                45430 non-null  float64
 16  poster_path            45047 non-null  str
 17  domain                 45430 non-null  str
dtypes: float64(5), int64(3), str(10)
memory usage: 6.2 MB

In [40]:
dim_items = dim_items[
    [
        "item_id",
        "source_item_id",
        "title",
        "description",
        "release_date",
        "runtime",
        "language",
        "popularity",
        "vote_average",
        "vote_count",
        "belongs_to_collection",
        "production_companies",
        "production_countries",
        "budget",
        "revenue",
        "poster_path",
        "domain"
    ]
]

In [41]:
dim_items["item_id"].nunique()

45430

In [42]:
dim_items.head()

,item_id,source_item_id,title,description,release_date,runtime,language,popularity,vote_average,vote_count,belongs_to_collection,production_companies,production_countries,budget,revenue,poster_path,domain
0,1,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",1995-10-30,81.0,en,21.946943,7.7,5415.0,"{'id': 10194, 'name': 'Toy Story Collection', ...","[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",30000000,373554033.0,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,movie
1,2,8844,Jumanji,When siblings Judy and Peter discover an encha...,1995-12-15,104.0,en,17.015539,6.9,2413.0,NaN,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",65000000,262797249.0,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,movie
2,3,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,1995-12-22,101.0,en,11.712900,6.5,92.0,"{'id': 119050, 'name': 'Grumpy Old Men Collect...","[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",0,0.0,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,movie
3,4,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",1995-12-22,127.0,en,3.859495,6.1,34.0,NaN,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o...",16000000,81452156.0,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,movie
4,5,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,1995-02-10,106.0,en,8.387519,5.7,173.0,"{'id': 96871, 'name': 'Father of the Bride Col...","[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o...",0,76578911.0,/e64sOI48hQXyru7naBFyssKFxVd.jpg,movie

In [43]:
item_map = dim_items[
    ["item_id", "source_item_id"]
]

In [44]:
item_genres = pd.read_csv("item_genres.csv")

In [45]:
item_genres = item_genres.merge(
    item_map,
    on="source_item_id",
    how="inner"
)

In [46]:
item_genres = item_genres[
    ["item_id", "genre"]
]

In [47]:
item_genres.info()

<class 'pandas.DataFrame'>
RangeIndex: 91006 entries, 0 to 91005
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   item_id  91006 non-null  int64
 1   genre    91006 non-null  str
dtypes: int64(1), str(1)
memory usage: 1.4 MB

In [48]:
item_genres.head()

   item_id      genre
0        1  Animation
1        1     Comedy
2        1     Family
3        2  Adventure
4        2    Fantasy

In [50]:
item_keywords = pd.read_csv("item_keywords.csv")

In [51]:
item_keywords = item_keywords.merge(
    item_map,
    on="source_item_id",
    how="inner"
)

In [52]:
item_keywords = item_keywords[
    ["item_id", "keyword"]
]

In [53]:
item_keywords.head()

   item_id     keyword
0        1    jealousy
1        1         toy
2        1         boy
3        1  friendship
4        1     friends

In [54]:
item_cast = pd.read_csv("item_cast.csv")

In [55]:
item_cast = item_cast.merge(
    item_map,
    on="source_item_id",
    how="inner"
)

In [56]:
item_cast = item_cast[
    ["item_id", "actor"]
]

In [57]:
item_cast.head()

   item_id          actor
0        1      Tom Hanks
1        1      Tim Allen
2        1    Don Rickles
3        1     Jim Varney
4        1  Wallace Shawn

In [58]:
item_directors = pd.read_csv("item_directors.csv")

In [59]:
item_directors = item_directors.merge(
    item_map,
    on="source_item_id",
    how="inner"
)

In [60]:
item_directors = item_directors[
    ["item_id", "director"]
]

In [61]:
item_directors.head()

   item_id         director
0        1    John Lasseter
1        2     Joe Johnston
2        3    Howard Deutch
3        4  Forest Whitaker
4        5    Charles Shyer

In [62]:
fact_interactions.head()

   user_id  source_item_id  rating   timestamp
0        1             197     1.0  1425941529
1        1           10474     4.5  1425942435
2        1             238     5.0  1425941523
3        1             240     5.0  1425941546
4        1             207     5.0  1425941556

In [63]:
fact_interactions = fact_interactions.merge(
    item_map,
    on="source_item_id",
    how="inner"
)

In [64]:
fact_interactions = fact_interactions[
    [
        "user_id",
        "item_id",
        "rating",
        "timestamp"
    ]
]

In [65]:
dim_users = pd.DataFrame({
    "user_id": fact_interactions["user_id"].unique()
})

In [66]:
dim_users.info()

<class 'pandas.DataFrame'>
RangeIndex: 270883 entries, 0 to 270882
Data columns (total 1 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  270883 non-null  int32
dtypes: int32(1)
memory usage: 1.0 MB

In [70]:
print(dim_items.shape)
print(dim_users.shape)
print(item_genres.shape)
print(item_keywords.shape)
print(item_cast.shape)
print(item_directors.shape)
print(fact_interactions.shape)

(45430, 17)
(270883, 1)
(91006, 2)
(156586, 2)
(202288, 2)
(48996, 2)
(25981567, 4)

In [71]:
item_genres["item_id"].isin(
    dim_items["item_id"]
).all()

np.True_

In [72]:
item_keywords["item_id"].isin(
    dim_items["item_id"]
).all()

np.True_

In [73]:
item_cast["item_id"].isin(
    dim_items["item_id"]
).all()

np.True_

In [74]:
item_directors["item_id"].isin(
    dim_items["item_id"]
).all()

np.True_

In [75]:
fact_interactions["item_id"].isin(
    dim_items["item_id"]
).all()

np.True_

In [82]:
import fastparquet

In [88]:
dim_items.to_parquet(
    f"{PROJECT_ROOT}/data/processed/movies/dim_items.parquet",
    engine="fastparquet",
    index=False
)

In [89]:
dim_items.to_parquet(
    f"{PROJECT_ROOT}/data/processed/movies/dim_items.parquet",
    engine="fastparquet",
    index=False
)

dim_users.to_parquet(
    f"{PROJECT_ROOT}/data/processed/movies/dim_users.parquet",
    engine="fastparquet",
    index=False
)

item_genres.to_parquet(
    f"{PROJECT_ROOT}/data/processed/movies/item_genres.parquet",
    engine="fastparquet",
    index=False
)

item_keywords.to_parquet(
    f"{PROJECT_ROOT}/data/processed/movies/item_keywords.parquet",
    engine="fastparquet",
    index=False
)

item_cast.to_parquet(
    f"{PROJECT_ROOT}/data/processed/movies/item_cast.parquet",
    engine="fastparquet",
    index=False
)

item_directors.to_parquet(
    f"{PROJECT_ROOT}/data/processed/movies/item_directors.parquet",
    engine="fastparquet",
    index=False
)

fact_interactions.to_parquet(
    f"{PROJECT_ROOT}/data/processed/movies/fact_interactions.parquet",
    engine="fastparquet",
    index=False
)

In [4]:
dim_items = pd.read_parquet(
    f"{PROJECT_ROOT}/data/processed/movies/dim_items.parquet",
    engine="fastparquet"
)

In [5]:
dim_items[
    [
        "belongs_to_collection",
        "production_companies",
        "production_countries"
    ]
].head()

,belongs_to_collection,production_companies,production_countries
0,"{'id': 10194, 'name': 'Toy Story Collection', ...","[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o..."
1,<NA>,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o..."
2,"{'id': 119050, 'name': 'Grumpy Old Men Collect...","[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o..."
3,<NA>,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_3166_1': 'US', 'name': 'United States o..."
4,"{'id': 96871, 'name': 'Father of the Bride Col...","[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_3166_1': 'US', 'name': 'United States o..."

In [6]:
def extract_collection_name(value):
    if pd.isna(value):
        return ""

    try:
        data = ast.literal_eval(value)
        return data.get("name", "")
    except:
        return ""

In [8]:
dim_items["collection_name"] = (
    dim_items["belongs_to_collection"]
    .apply(extract_collection_name)
)

In [10]:
def extract_company_names(value):
    if pd.isna(value):
        return ""

    try:
        data = ast.literal_eval(value)

        return " ".join(
            company["name"]
            for company in data
            if "name" in company
        )

    except:
        return ""

In [11]:
dim_items["company_names"] = (
    dim_items["production_companies"]
    .apply(extract_company_names)
)

In [12]:
def extract_country_names(value):
    if pd.isna(value):
        return ""

    try:
        data = ast.literal_eval(value)

        return " ".join(
            country["name"]
            for country in data
            if "name" in country
        )

    except:
        return ""

In [13]:
dim_items["country_names"] = (
    dim_items["production_countries"]
    .apply(extract_country_names)
)

In [15]:
dim_items = dim_items[
    [
        "item_id",
        "source_item_id",
        "title",
        "description",
        "release_date",
        "runtime",
        "language",
        "popularity",
        "vote_average",
        "vote_count",
        "collection_name",
        "company_names",
        "country_names",
        "budget",
        "revenue",
        "poster_path",
        "domain"
    ]
].copy()

In [16]:
dim_items.head()

,item_id,source_item_id,title,description,release_date,runtime,language,popularity,vote_average,vote_count,collection_name,company_names,country_names,budget,revenue,poster_path,domain
0,1,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",1995-10-30,81.0,en,21.946943,7.7,5415.0,Toy Story Collection,Pixar Animation Studios,United States of America,30000000,373554033.0,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,movie
1,2,8844,Jumanji,When siblings Judy and Peter discover an encha...,1995-12-15,104.0,en,17.015539,6.9,2413.0,,TriStar Pictures Teitler Film Interscope Commu...,United States of America,65000000,262797249.0,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,movie
2,3,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,1995-12-22,101.0,en,11.712900,6.5,92.0,Grumpy Old Men Collection,Warner Bros. Lancaster Gate,United States of America,0,0.0,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,movie
3,4,31357,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",1995-12-22,127.0,en,3.859495,6.1,34.0,,Twentieth Century Fox Film Corporation,United States of America,16000000,81452156.0,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,movie
4,5,11862,Father of the Bride Part II,Just when George Banks has recovered from his ...,1995-02-10,106.0,en,8.387519,5.7,173.0,Father of the Bride Collection,Sandollar Productions Touchstone Pictures,United States of America,0,76578911.0,/e64sOI48hQXyru7naBFyssKFxVd.jpg,movie

In [17]:
dim_items.to_parquet("dim_items.parquet", engine="fastparquet", index=False)

## keywords

In [119]:
keywords.info()

<class 'pandas.DataFrame'>
RangeIndex: 46419 entries, 0 to 46418
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        46419 non-null  int64
 1   keywords  46419 non-null  str
dtypes: int64(1), str(1)
memory usage: 725.4 KB

In [120]:
keywords.head()

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

In [121]:
keywords["id"].duplicated().sum()

np.int64(987)

In [123]:
keywords[
    keywords["id"].duplicated(keep=False)
].sort_values("id").head(6)

         id                                           keywords
37095  1998  [{'id': 417, 'name': 'corruption'}, {'id': 612...
36138  1998  [{'id': 417, 'name': 'corruption'}, {'id': 612...
36822  3025  [{'id': 212, 'name': 'london england'}, {'id':...
35865  3025  [{'id': 212, 'name': 'london england'}, {'id':...
35999  3692  [{'id': 470, 'name': 'spy'}, {'id': 591, 'name...
36956  3692  [{'id': 470, 'name': 'spy'}, {'id': 591, 'name...

In [126]:
keywords_clean = (
    keywords
    .drop_duplicates(subset=["id"])
    .copy()
)

In [127]:
keywords_clean.info()

<class 'pandas.DataFrame'>
Index: 45432 entries, 0 to 46418
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        45432 non-null  int64
 1   keywords  45432 non-null  str
dtypes: int64(1), str(1)
memory usage: 1.0 MB

In [128]:
keywords_clean = keywords_clean.rename(
    columns={
        "id": "source_item_id"
    }
)

In [129]:
set_movies = set(movies_metadata_clean["source_item_id"])
set_keywords = set(keywords_clean["source_item_id"])

print("Movies:", len(set_movies))
print("Keywords:", len(set_keywords))
print("Overlap:", len(set_movies & set_keywords))

Movies: 45430
Keywords: 45432
Overlap: 45429

In [130]:
import ast

def extract_keywords(keyword_str):
    try:
        items = ast.literal_eval(keyword_str)
        return [x["name"] for x in items]
    except:
        return []

In [131]:
keywords_clean["keyword_list"] = (
    keywords_clean["keywords"]
    .apply(extract_keywords)
)

In [132]:
item_keywords = (
    keywords_clean[
        ["source_item_id", "keyword_list"]
    ]
    .explode("keyword_list")
    .rename(
        columns={
            "keyword_list": "keyword"
        }
    )
)

In [134]:
item_keywords = item_keywords[
    item_keywords["keyword"].notna()
]

In [135]:
item_keywords.info()

<class 'pandas.DataFrame'>
Index: 156602 entries, 0 to 46415
Data columns (total 2 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   source_item_id  156602 non-null  int64
 1   keyword         156602 non-null  str
dtypes: int64(1), str(1)
memory usage: 3.6 MB

In [141]:
item_keywords.head()

   source_item_id     keyword
0             862    jealousy
0             862         toy
0             862         boy
0             862  friendship
0             862     friends

In [139]:
item_keywords["keyword"].nunique()

19956

In [142]:
keywords_clean.info()

<class 'pandas.DataFrame'>
Index: 45432 entries, 0 to 46418
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   source_item_id  45432 non-null  int64
 1   keywords        45432 non-null  str
 2   keyword_list    45432 non-null  object
dtypes: int64(1), object(1), str(1)
memory usage: 1.4+ MB

In [143]:
keywords_clean.head()

,source_item_id,keywords,keyword_list
0,862,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...","[jealousy, toy, boy, friendship, friends, riva..."
1,8844,"[{'id': 10090, 'name': 'board game'}, {'id': 1...","[board game, disappearance, based on children'..."
2,15602,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392...","[fishing, best friend, duringcreditsstinger, o..."
3,31357,"[{'id': 818, 'name': 'based on novel'}, {'id':...","[based on novel, interracial relationship, sin..."
4,11862,"[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...","[baby, midlife crisis, confidence, aging, daug..."

In [144]:
keywords_clean.to_csv(
    "keywords_clean.csv",
    index=False
)

In [145]:
item_keywords.to_csv(
    "item_keywords.csv",
    index=False
)

In [175]:
item_keywords["source_item_id"].nunique()

31092

## credits

In [146]:
credits.info()

<class 'pandas.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45476 non-null  str
 1   crew    45476 non-null  str
 2   id      45476 non-null  int64
dtypes: int64(1), str(2)
memory usage: 1.0 MB

In [147]:
credits.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [148]:
credits["id"].duplicated().sum()

np.int64(44)

In [151]:
credits[
    credits["id"].duplicated(keep=False)
].sort_values("id").head(6)

,cast,crew,id
25950,"[{'cast_id': 12, 'character': 'The Creature', ...","[{'credit_id': '52fe4380c3a36847f80590dd', 'de...",3057
25885,"[{'cast_id': 12, 'character': 'The Creature', ...","[{'credit_id': '52fe4380c3a36847f80590dd', 'de...",3057
5865,"[{'cast_id': 15, 'character': 'Chuck Barris', ...","[{'credit_id': '52fe43e2c3a36847f80760b5', 'de...",4912
33838,"[{'cast_id': 15, 'character': 'Chuck Barris', ...","[{'credit_id': '52fe43e2c3a36847f80760a9', 'de...",4912
9165,"[{'cast_id': 11, 'character': 'Jef Costello', ...","[{'credit_id': '52fe440ac3a36847f807ee01', 'de...",5511
7345,"[{'cast_id': 11, 'character': 'Jef Costello', ...","[{'credit_id': '52fe440ac3a36847f807ee01', 'de...",5511

In [152]:
set_movies = set(movies_metadata_clean["source_item_id"])
set_credits = set(credits["id"])

print("Movies:", len(set_movies))
print("Credits:", len(set_credits))
print("Overlap:", len(set_movies & set_credits))

Movies: 45430
Credits: 45432
Overlap: 45429

In [153]:
credits_clean = (
    credits
    .drop_duplicates(subset=["id"])
    .copy()
)

In [154]:
credits_clean = credits_clean.rename(
    columns={"id": "source_item_id"}
)

In [155]:
def extract_cast(cast_str, top_n=5):
    try:
        cast_list = ast.literal_eval(cast_str)
        return [x["name"] for x in cast_list[:top_n]]
    except:
        return []

In [156]:
credits_clean["cast_list"] = (
    credits_clean["cast"]
    .apply(extract_cast)
)

In [157]:
item_cast = (
    credits_clean[
        ["source_item_id", "cast_list"]
    ]
    .explode("cast_list")
    .rename(
        columns={
            "cast_list": "actor"
        }
    )
)

In [159]:
item_cast = item_cast[
    item_cast["actor"].notna()
]

In [160]:
item_cast.info()

<class 'pandas.DataFrame'>
Index: 202303 entries, 0 to 45474
Data columns (total 2 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   source_item_id  202303 non-null  int64
 1   actor           202303 non-null  str
dtypes: int64(1), str(1)
memory usage: 4.6 MB

In [162]:
item_cast.head(20)

   source_item_id            actor
0             862        Tom Hanks
0             862        Tim Allen
0             862      Don Rickles
0             862       Jim Varney
0             862    Wallace Shawn
1            8844   Robin Williams
1            8844    Jonathan Hyde
1            8844    Kirsten Dunst
1            8844   Bradley Pierce
1            8844      Bonnie Hunt
2           15602   Walter Matthau
2           15602      Jack Lemmon
2           15602      Ann-Margret
2           15602     Sophia Loren
2           15602     Daryl Hannah
3           31357  Whitney Houston
3           31357   Angela Bassett
3           31357   Loretta Devine
3           31357      Lela Rochon
3           31357    Gregory Hines

In [ ]:
item_cast["source_item_id"].nunique()

215090

In [163]:
def extract_directors(crew_str):
    try:
        crew_list = ast.literal_eval(crew_str)

        return [
            person["name"]
            for person in crew_list
            if person.get("job") == "Director"
        ]
    except:
        return []

In [164]:
credits_clean["director_list"] = (
    credits_clean["crew"]
    .apply(extract_directors)
)

In [165]:
item_directors = (
    credits_clean[
        ["source_item_id", "director_list"]
    ]
    .explode("director_list")
    .rename(
        columns={
            "director_list": "director"
        }
    )
)

In [167]:
item_directors = item_directors[
    item_directors["director"].notna()
]

In [176]:
item_directors.info()

<class 'pandas.DataFrame'>
Index: 48999 entries, 0 to 45475
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   source_item_id  48999 non-null  int64
 1   director        48999 non-null  str
dtypes: int64(1), str(1)
memory usage: 1.1 MB

In [169]:
item_directors.head()

   source_item_id         director
0             862    John Lasseter
1            8844     Joe Johnston
2           15602    Howard Deutch
3           31357  Forest Whitaker
4           11862    Charles Shyer

In [174]:
item_directors["source_item_id"].nunique()

44545

In [177]:
item_directors.groupby("source_item_id").size().value_counts().head(10)

1     41350
2      2714
3       282
4        75
5        39
6        23
7        19
8        10
10        7
11        6
Name: count, dtype: int64

In [178]:
item_cast.to_csv(
    "item_cast.csv",
    index=False
)

In [179]:
item_directors.to_csv(
    "item_directors.csv",
    index=False
)

In [180]:
credits_clean.info()

<class 'pandas.DataFrame'>
Index: 45432 entries, 0 to 45475
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cast            45432 non-null  str
 1   crew            45432 non-null  str
 2   source_item_id  45432 non-null  int64
 3   cast_list       45432 non-null  object
 4   director_list   45432 non-null  object
dtypes: int64(1), object(2), str(2)
memory usage: 2.1+ MB

In [181]:
credits_clean.head()

,cast,crew,source_item_id,cast_list,director_list
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862,"[Tom Hanks, Tim Allen, Don Rickles, Jim Varney...",[John Lasseter]
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844,"[Robin Williams, Jonathan Hyde, Kirsten Dunst,...",[Joe Johnston]
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602,"[Walter Matthau, Jack Lemmon, Ann-Margret, Sop...",[Howard Deutch]
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357,"[Whitney Houston, Angela Bassett, Loretta Devi...",[Forest Whitaker]
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862,"[Steve Martin, Diane Keaton, Martin Short, Kim...",[Charles Shyer]

In [182]:
credits_clean.to_csv(
    "credits_clean.csv",
    index=False
)